version: '3.9'

services:
  database:
    image: docker.arvancloud.ir/postgres:latest
    restart: always
    volumes:
      - book_library_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "pgpassword"
      POSTGRES_USER: "pgadmin"
      POSTGRES_DB: "book"

  app:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn -w 4 -b 0.0.0.0:8000 book_library.wsgi:application"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - database
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  book_library_db: