# Generated by Django 5.1 on 2024-09-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_management', '0002_rename_publish_at_book_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
